### ISSUE TITLE
Tx.transactionalWithIsolation broken on rollback

### ISSUE THREAD

**Issue by haf** [mausch/FsSql#22]
**Summary**

When using `transactionalWithIsolation` the library doesn't handle the disposal/close of the IDbConnection properly with respect to the interaction with the transaction.

Justification: it should not matter what isolation level I set on the transaction from a runtime-perspective, only from a database-transaction perspective. Corollary; there is always a transaction level active, even if it's implicit, so making it explicit should not matter.

**Working test**

``` fsharp
    testCase "can execute serialisable tx" <| fun _ ->
      let cm = Sql.withNewConnection (fun () -> Conn.sqlite_open' InMemory)
      let select_one m = Sql.execScalar m "select 1" []
      let select_one =
        select_one
        |> Tx.transactional2
        |> Tx.transactionalWithIsolation IsolationLevel.Serializable
      let res = select_one cm
      Assert.Equal("Can execute tx", Tx.TxResult.Commit(Some 1L), res)
```

**Failing test case**

``` fsharp
    testCase "can execute serialisable tx 2" <| fun _ ->
      let tx = Tx.TransactionBuilder()
      let cm = Sql.withNewConnection (fun () -> Conn.sqlite_open' InMemory)
      let select_one = tx {
        let! a = Tx.execScalar "select 1" []
        let a : int64 = a |> Option.get
        if 1 = 1 then // comment out this, next line, to make test pass
          do! Tx.rollback 3L
        let! b = Tx.execScalar "select 1" []
        let b : int64 = b |> Option.get
        return a + b
      }
      let select_one = select_one |> Tx.transactionalWithIsolation IsolationLevel.Serializable
      let res = select_one cm
      Assert.Equal("Can execute tx", Tx.TxResult.Rollback 3L, res)
```

**Stack trace**:

```
smoke/can execute serialisable tx 2: Exception: System.ArgumentNullException: Argument cannot be null.
Parameter name: No connection associated with this transaction
  at Mono.Data.Sqlite.SqliteTransaction.IsValid (Boolean throwError) [0x00011] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteTransaction.cs:148 
  at Mono.Data.Sqlite.SqliteTransaction.Rollback () [0x00000] in /private/tmp/source-mono-mac-3.12.0-branch-32/bockbuild-mono-3.12.0-branch/profiles/mono-mac-xamarin/build-root/mono-3.12.0/mcs/class/Mono.Data.Sqlite/Mono.Data.Sqlite_2.0/SQLiteTransaction.cs:127 
  at Tx+transactionalWithIsolation@13[Tx+TxResult`2[System.Int64,System.Int64]].Invoke (IDbConnection conn) [0x00000] in <filename unknown>:0 
  at FsSqlPrelude.withResource[IDbConnection,TxResult`2] (Microsoft.FSharp.Core.FSharpFunc`2 create, Microsoft.FSharp.Core.FSharpFunc`2 dispose, Microsoft.FSharp.Core.FSharpFunc`2 action) [0x00000] in <filename unknown>:0 
  at Tx.transactionalWithIsolation[TxResult`2] (IsolationLevel isolation, Microsoft.FSharp.Core.FSharpFunc`2 f, ConnectionManager cmgr) [0x00000] in <filename unknown>:0 
  at logibit.Sqlite.Tests.Smoke+select_one@67-11.Invoke (ConnectionManager cmgr) [0x00000] in /Users/henrik.feldt/dev/logibit/logibit.web/src/logibit.sqlite.tests/Smoke.fs:67 
  at logibit.Sqlite.Tests.Smoke+smoke@54-4.Invoke (Microsoft.FSharp.Core.Unit _arg5) [0x0003e] in /Users/henrik.feldt/dev/logibit/logibit.web/src/logibit.sqlite.tests/Smoke.fs:68 
  at Fuchu.Impl+evalTestList@258-1.Invoke (System.Tuple`2 tupledArg) [0x00000] in <filename unknown>:0
```

**Comment by mausch** [comment]
Hmm, I think I know what the problem is... the exception thrown in https://github.com/mausch/FsSql/blob/master/FsSql/Transactions.fs#L24 gets interpreted as a `Failed` instead of a `Rollback`. Can you check if that's the case, by changing the final Assert in your failing test case?

**Comment by haf** [comment]
The exception isn't caught.

**Comment by haf** [comment]
What I mean is that the final Assert isn't reached, because the exception isn't caught. Sorry if I was being too frugal with my words.

**Comment by mausch** [comment]
No worries, I understood what you meant. I just added this failing test to the project.

**Comment by mausch** [comment]
Bloody stateful mutable weakly-typed ADO.NET objects... it's incredibly hard to reason about things like that. I'm considering first creating a proper typed model of transactions and connections that avoid things like http://stackoverflow.com/questions/19559715/when-does-sqlconnection-does-not-support-parallel-transactions-happen or http://stackoverflow.com/questions/6358806/this-sqltransaction-has-completed-it-is-no-longer-usable-configuration-er or this.

**Comment by haf** [comment]
Better you being the poor sod to reason about weak interaction of spooky mutable objects at a distance, do a great library and save the next man from sure and imminent death by mutation. ;)

**Comment by mausch** [comment]
Absolutely, that is one of the goals of FsSql.

I revised the whole Tx module and made a few breaking changes. First I made I made `transactionalWithIsolation` total, returning TxResult instead of throwing exceptions (what was I thinking). This change made `transactional2` unnecessary so I removed it (it also had the worst name ever).
That fixed the issue you describe here.

While I was at it, I also parameterized the Tx builder on the isolation level and removed the nonsense functions that applied "policies" on transactional functions.

There are still things I don't like but this should be much better than what I had before.

If you're ok with these changes I can release v2.0.

**Comment by haf** [comment]
Yes, that sounds great. :shipit:

**Comment by haf** [comment]
I would love if you could publish a nuget with this, or I'll have to fork this library too :(

**Comment by mausch** [comment]
Ooops, forgot about this, sorry.
Pushed: http://www.nuget.org/packages/FsSql/2.0.0

**Comment by haf** [comment]
This is still broken. Did you incorporate my test?

``` fsharp
    testCase "can execute serialisable tx 2" <| fun _ ->
      //Tests.skiptest "https://github.com/mausch/FsSql/issues/22"
      let tx = Tx.TransactionBuilder()
      let cm = Sql.withNewConnection (fun () -> SqliteConn.openConnType InMemory)
      let select_one = tx {
        let! a = Tx.execScalar "select 1" []
        let a : int64 = a |> Option.get
        if 1 = 1 then // comment out this, next line, to make test pass
          do! Tx.rollback 3L
        let! b = Tx.execScalar "select 1" []
        let b : int64 = b |> Option.get
        return a + b
      }
      let select_one = select_one |> Tx.transactionalWithIsolation IsolationLevel.Serializable
      let res = select_one cm
      Assert.Equal("Can execute tx", Tx.TxResult.Rollback 3L, res)
```

**Comment by mausch** [comment]
Yes, that test is in https://github.com/mausch/FsSql/blob/6bf3f5089429379d0dd86ca998004b2dea5b4806/FsSql.Tests/Tests.fs#L672

**Comment by haf** [comment]
It's not working for me. This is the output I get:

```
smoke/can execute serialisable tx 2: Failed: 
Can execute tx
Expected: Rollback 3L
Actual: Commit (Rollback 3L)

 (00:00:00.0507759)
smoke/can execute serialisable tx 2: Failed: 
Can execute tx
Expected: Rollback 3L
Actual: Commit (Rollback 3L)
```

I'm running on Mono 3.12.1 on OS X. Did you test on that platform?

**Comment by mausch** [comment]
IIRC I only tested on Windows. I'll write a dockerfile to make it easier to test on Mono...

**Comment by mausch** [comment]
Well, running docker on Travis is a hassle so I'm giving up on Travis for now, but I did test it locally with docker / mono 3.12 and all the tests pass. https://github.com/mausch/FsSql/commit/661003ea54d09a7c2ec803e35444f8fca980111a

**Comment by haf** [comment]
Strange; it might have something to do with how or what version of sqlite we link to. What version are you using? I'm at `3.7.13 2012-07-17 17:46:21 65035912264e3acbced5a3e16793327f0a2f17bb`, you?

**Comment by mausch** [comment]
Seems I have an ancient version of Sqlite from 5 years ago: https://github.com/mausch/FsSql/tree/master/lib . I'll look into updating it tonight...

**Comment by mausch** [comment]
Actually the Mono build uses `Mono.Data.Sqlite`. https://github.com/mausch/FsSql/blob/master/FsSql.Tests/FsSql.Tests.fsproj#L75

And I just tried updating the .NET build to http://www.nuget.org/packages/System.Data.SQLite.Core/1.0.96 and I only had to change the expected exception in https://github.com/mausch/FsSql/blob/master/FsSql.Tests/Tests.fs#L248 to a NullReferenceException, not a major change. All tests passed.
