### ISSUE TITLE
Tests don't run on mono

### ISSUE THREAD

**Issue by haf** [mausch/FsSql#25]
```
insert then get (memory db): Exception: System.DllNotFoundException: System.Data.SQLite.DLL
```

**Comment by haf** [comment]
Copy these lines to the test fsproj file:

https://github.com/haf/miTLS/blob/master/src/DB/DB.fsproj#L60-L63

**Comment by mausch** [comment]
Thanks, I'll take a look at these PRs when I get home tonight.
